export const ActionType = {
    LOADING: "context/LOADING",
    LOADED: "context/LOADED",
    CHANGE_THEME: "context/CHANGE_THEME",
    CHANGE_CONNECTION: 'context/CHANGE_CONNECTION',
    CHANGE_VERSION:'context/CHANGE_VERSION',
    CHANGE_USER: 'context/CHANGE_USER',
    LOGGEDIN: 'context/LOGGEDIN',
    RETRIEVECODE :'context/RETRIEVECODE',
    LOGOUT: 'context/LOGOUT',
    FIELD_CHANGE: 'context/FIELD_CHANGE',
    SELECT_CONVERSATION: 'context/SELECT_CONVERSATION'
}