export const ActionType = {

    REQUESTING_ITEMS: "cert/REQUESTING_ITEMS",
    REQUESTED_ITEMS: "cert/REQUEST_ITEMS",
    REQUESTING_ITEM:'cert/REQUESTING_ITEM',
    REQUESTED_ITEM: 'cert/REQUESTED_ITEM',
    COMMITING_ITEM: 'cert/COMMITING_ITEM',
    COMMITED_ITEM:'cert/COMMITED_ITEM'

}